name: ci-cd

on:
  workflow_dispatch:

env:
  TF_IN_AUTOMATION: 1

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  ci:
    runs-on: ubuntu-22.04
    environment: prod
    outputs:
      plan-exitcode: ${{ steps.plan.outputs.exitcode }}
    steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        allow-no-subscriptions: true

    - uses: actions/checkout@v3

    - name: Terraform plan composite action
      id: plan
      uses: ./.github/actions/tf-plan
      with:
        arm-client-id: ${{ secrets.AZURE_CLIENT_ID }}
        arm-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        tf-root-dir: ${{ github.workspace }}
        tf-version: ~1.3.0

  cd:
    if: github.ref == 'refs/heads/main' && needs.ci.outputs.plan-exitcode == '2'
    needs: ci
    runs-on: ubuntu-22.04
    environment: prod-approval
    steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        allow-no-subscriptions: true

    - uses: actions/checkout@v3

    - name: Terraform apply composite action
      uses: ./.github/actions/tf-apply
      with:
        arm-client-id: ${{ secrets.AZURE_CLIENT_ID }}
        arm-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        tf-root-dir: ${{ github.workspace }}
        tf-version: ~1.3.0
